

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - MQTT_BROKER=mqtt://mosquitto:1883
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped