version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mosquitto

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend